<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ISIPL-PUNV-L406.local" failures="1" tests="3" name="Default test" time="0.082" errors="0" timestamp="2024-08-22T08:52:22 IST">
  <testcase classname="testNG_Day2.AttributeDemo2" name="Demo" time="0.012"/>
  <testcase classname="testNG_Day2.AttributeDemo2" name="Demo1" time="0.002"/>
  <testcase classname="testNG_Day2.AttributeDemo2" name="TestDP" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method void testNG_Day2.AttributeDemo2.TestDP(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : TestData in class testNG_Day2.AttributeDemo">
      <![CDATA[org.testng.TestNGException: 
Method void testNG_Day2.AttributeDemo2.TestDP(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : TestData in class testNG_Day2.AttributeDemo
at org.testng.internal.Parameters.findDataProvider(Parameters.java:561)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestDP -->
</testsuite> <!-- Default test -->
